services:
  - type: web
    name: medusa-backend
    env: node
    rootDir: apps/medusa
    plan: free
    buildCommand: |
      yarn install --frozen-lockfile
      yarn medusa build
      echo "==== Medusa build terminado ===="
      ls -la .medusa/client
      mkdir -p .medusa/server/admin
      cp -r .medusa/client/* .medusa/server/admin/
      echo "==== Admin copiado correctamente ===="
      yarn build
      echo "==== Backend build terminado ===="
    startCommand: PORT=${PORT:-9000} yarn start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=require
      - key: PGSSLMODE
        value: require
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_KX87bUyBadzP
      - key: DB_HOST
        value: ep-sweet-rice-ac0urkja-pooler.sa-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: medusa2
      - key: DB_SSL
        value: true
      - key: REDIS_URL
        value: rediss://default:AW83AAIjcDE2MmU0NGU5OGU3MGE0Y2I4OWM5OTAyM2EwZjQ0YjI5ZXAxMA@ultimate-elk-28471.upstash.io:6379
      - key: STORE_CORS
        value: http://localhost:8000,https://docs.medusajs.com
      - key: ADMIN_CORS
        value: http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
      - key: AUTH_CORS
        value: http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
      - key: JWT_SECRET
        value: supersecret
      - key: COOKIE_SECRET
        value: supersecret
      - key: ADMIN_BACKEND_URL
        value: http://localhost:9000
      - key: STRIPE_API_KEY
        value: sk_test_51RHbG3Gg75hGRlZOIitZevGR9ED7wtvla8se0fPc7MNVM9hLxiJXKIaWRjWZmtSmqUMnxWSwcx4adDoLKk6Ic72000H8m2hRMU
